// HMD Secure AI-Native CRM — Seed data.
// Pure static definitions separated from crm.ts logic.

import { defaultOfferWorkflow } from "./crm.ts";
import type {
  User,
  Account,
  Contact,
  ProductCatalogItem,
  ServiceCatalogItem,
  Deal,
  ServiceContract,
  CaseRecord,
  Offer,
  Activity,
  AiInsight,
  Notification,
} from "./crm.ts";

export const seedUsers: User[] = [
  { id: "u_aino", name: "Aino Lahti", email: "aino.lahti@hmd.example", role: "sales_rep", initials: "AL", title: "Sales Representative" },
  { id: "u_elias", name: "Elias Niemi", email: "elias.niemi@hmd.example", role: "sales_rep", initials: "EN", title: "Sales Representative" },
  { id: "u_sara", name: "Sara Miettinen", email: "sara.miettinen@hmd.example", role: "tam", initials: "SM", title: "Technical Account Manager" },
  { id: "u_oskari", name: "Oskari Lehto", email: "oskari.lehto@hmd.example", role: "tam", initials: "OL", title: "Technical Account Manager" },
  { id: "u_mikael", name: "Mikael Korhonen", email: "mikael.korhonen@hmd.example", role: "sales_manager", initials: "MK", title: "Sales Manager" },
  { id: "u_veera", name: "Veera Salonen", email: "veera.salonen@hmd.example", role: "finance", initials: "VS", title: "Finance" },
  { id: "u_admin", name: "Leena Virtanen", email: "leena.virtanen@hmd.example", role: "admin", initials: "LV", title: "Administrator" },
];

export const seedAccounts: Account[] = [
  {
    id: "a_nordcom",
    name: "Nordcom Mobility",
    domain: "nordcom.example",
    address: "Speicherstadt 4, 20457 Hamburg, Germany",
    vatId: "DE 812 4471 90",
    industry: "Field logistics",
    region: "DACH",
    ownerId: "u_aino",
    lifecycle: "Customer · Expanding",
    sites: 6,
    summary: "Six-site logistics operator rolling rugged devices out to field crews after a successful first wave.",
    since: "Mar 2023",
  },
  {
    id: "a_vektor",
    name: "Vektor Logistics",
    domain: "vektor.example",
    address: "Hamnvägen 12, 211 19 Malmö, Sweden",
    vatId: "SE 556 921 0044",
    industry: "Transport & haulage",
    region: "Nordics",
    ownerId: "u_elias",
    lifecycle: "Customer · Stable",
    sites: 3,
    summary: "Reseller-led haulage account; pricing is approved and the offer is live with the end customer.",
    since: "Sep 2022",
  },
  {
    id: "a_lumen",
    name: "Lumen Public Safety",
    domain: "lumen.example",
    address: "2 Albert Square, Manchester M2 5PT, United Kingdom",
    vatId: "GB 422 118 06",
    industry: "Public safety",
    region: "UK & IE",
    ownerId: "u_aino",
    lifecycle: "Customer · At risk",
    sites: 11,
    summary: "Largest public-safety account; the frame renewal is in contract negotiation and the close date has slipped.",
    since: "Jan 2021",
  },
  {
    id: "a_arctic",
    name: "Arctic Grid",
    domain: "arcticgrid.example",
    address: "Kungsgatan 8, 111 43 Stockholm, Sweden",
    vatId: "SE 559 002 7781",
    industry: "Energy & utilities",
    region: "Nordics",
    ownerId: "u_elias",
    lifecycle: "Prospect · Early",
    sites: 3,
    summary: "New utilities prospect in discovery; the device trajectory is not yet captured across its three sites.",
    since: "May 2026",
  },
  {
    id: "a_halcyon",
    name: "Halcyon Facilities",
    domain: "halcyon.example",
    address: "Meir 24, 2000 Antwerp, Belgium",
    vatId: "BE 0712 994 331",
    industry: "Facilities management",
    region: "Benelux",
    ownerId: "u_elias",
    lifecycle: "Customer · Expanding",
    sites: 4,
    summary: "Facilities operator running a 120-device pilot with two follow-on markets identified in the account plan.",
    since: "Nov 2023",
  },
];

export const seedContacts: Contact[] = [
  { id: "c_nordcom_1", accountId: "a_nordcom", name: "Marit Brandt", email: "m.brandt@nordcom.example", phone: "+49 40 553 118", roleType: "tech_decision_maker", primary: true },
  { id: "c_nordcom_2", accountId: "a_nordcom", name: "Tobias Reiner", email: "t.reiner@nordcom.example", phone: "+49 40 553 207", roleType: "budget_holder" },
  { id: "c_nordcom_3", accountId: "a_nordcom", name: "Lena Vogt", email: "l.vogt@nordcom.example", phone: "+49 40 553 442", roleType: "influencer" },
  { id: "c_vektor_1", accountId: "a_vektor", name: "Henrik Sø", email: "h.so@vektor.example", phone: "+46 40 661 220", roleType: "budget_holder", primary: true },
  { id: "c_vektor_2", accountId: "a_vektor", name: "Paavo Rinne", email: "p.rinne@northbound.example", phone: "+358 9 477 010", roleType: "influencer" },
  { id: "c_lumen_1", accountId: "a_lumen", name: "DCI Rowan Hale", email: "r.hale@lumen.example", phone: "+44 161 200 7788", roleType: "budget_holder", primary: true },
  { id: "c_lumen_2", accountId: "a_lumen", name: "Priya Anand", email: "p.anand@lumen.example", phone: "+44 161 200 7790", roleType: "financial_decision_maker" },
  { id: "c_lumen_3", accountId: "a_lumen", name: "Gareth Pugh", email: "g.pugh@lumen.example", phone: "+44 161 200 7795", roleType: "influencer" },
  { id: "c_arctic_1", accountId: "a_arctic", name: "Sofia Lindqvist", email: "s.lindqvist@arcticgrid.example", phone: "+46 8 120 5530", roleType: "tech_decision_maker", primary: true },
  { id: "c_halcyon_1", accountId: "a_halcyon", name: "Bram de Vries", email: "b.devries@halcyon.example", phone: "+32 3 226 1140", roleType: "budget_holder", primary: true },
  { id: "c_halcyon_2", accountId: "a_halcyon", name: "Anouk Jansen", email: "a.jansen@halcyon.example", phone: "+32 3 226 1152", roleType: "tech_decision_maker" },
];

export const seedProducts: ProductCatalogItem[] = [
  { id: "p_xr21", name: "HMD XR-21 rugged 5G", category: "Device", listPrice: 466, retired: false },
  { id: "p_t30", name: "HMD T-30 field tablet", category: "Device", listPrice: 612, retired: false },
  { id: "p_pulse", name: "HMD Pulse handheld", category: "Device", listPrice: 312, retired: false },
  { id: "p_sled", name: "HMD Edge scanner sled", category: "Accessory", listPrice: 128, retired: false },
  { id: "p_xr11", name: "HMD XR-11 (previous gen)", category: "Device", listPrice: 388, retired: true },
];

export const seedServices: ServiceCatalogItem[] = [
  { id: "s_fota", name: "FOTA license", serviceType: "Software license", isThirdParty: false, retired: false },
  { id: "s_emm", name: "EMM", serviceType: "Device management platform", isThirdParty: false, retired: false },
  { id: "s_tech_compat", name: "Technical compatibility", serviceType: "Validation", isThirdParty: false, retired: false },
  { id: "s_mdm", name: "Secure MDM", serviceType: "Device management", isThirdParty: false, retired: false },
  { id: "s_lifecycle", name: "Device Lifecycle Management", serviceType: "Managed service", isThirdParty: false, retired: false },
  { id: "s_warranty", name: "Extended Warranty (3 yr)", serviceType: "Warranty", isThirdParty: false, retired: false },
  { id: "s_repair", name: "Onsite Repair & Swap", serviceType: "Field service", isThirdParty: true, retired: false },
  { id: "s_sim", name: "SIM Provisioning", serviceType: "Connectivity", isThirdParty: true, retired: false },
];

export const seedDeals: Deal[] = [
  {
    id: "d_nordcom",
    accountId: "a_nordcom",
    parentDealId: "d_nordcom_pilot",
    ownerId: "u_aino",
    title: "Field crew rollout — wave 2",
    stage: "customer_testing",
    leadValidated: true,
    channel: "direct",
    isPilot: false,
    expectedClose: "2026-07-18",
    updatedAt: "2026-05-26",
    createdAt: "2026-03-02",
    deviceUnitPrice: 466,
    devicePhases: [
      { period: "2026-Q3", units: 380 },
      { period: "2026-Q4", units: 420 },
      { period: "2027-Q2", units: 560 },
      { period: "2027-Q4", units: 300 },
    ],
  },
  {
    id: "d_nordcom_pilot",
    accountId: "a_nordcom",
    parentDealId: null,
    ownerId: "u_aino",
    title: "Pilot — wave 1 (50 devices)",
    stage: "closed",
    channel: "direct",
    isPilot: true,
    expectedClose: "2026-02-12",
    updatedAt: "2026-02-12",
    createdAt: "2025-11-04",
    deviceUnitPrice: 466,
    devicePhases: [{ period: "2026-Q1", units: 50 } as DevicePhase],
  },
  {
    id: "d_vektor",
    accountId: "a_vektor",
    parentDealId: null,
    ownerId: "u_elias",
    title: "Driver terminal refresh",
    stage: "offer",
    leadValidated: true,
    channel: "reseller",
    isPilot: false,
    expectedClose: "2026-09-04",
    updatedAt: "2026-06-12",
    createdAt: "2026-04-19",
    deviceUnitPrice: 312,
    devicePhases: [
      { period: "2026-Q4", units: 300 },
      { period: "2027-Q1", units: 540 },
      { period: "2027-Q3", units: 420 },
    ],
  },
  {
    id: "d_lumen",
    accountId: "a_lumen",
    parentDealId: null,
    ownerId: "u_aino",
    title: "Frame renewal 2026–2029",
    stage: "final_negotiation",
    leadValidated: true,
    channel: "direct",
    isPilot: false,
    expectedClose: "2026-06-06",
    updatedAt: "2026-06-07",
    createdAt: "2026-01-22",
    deviceUnitPrice: 612,
    devicePhases: [
      { period: "2026-Q3", units: 360 },
      { period: "2027-Q1", units: 640 },
      { period: "2027-Q4", units: 520 },
      { period: "2028-Q2", units: 300 },
    ],
  },
  {
    id: "d_lumen_bodyworn",
    accountId: "a_lumen",
    parentDealId: null,
    ownerId: "u_aino",
    title: "Body-worn device program (contract signed)",
    stage: "closed",
    leadValidated: true,
    channel: "direct",
    isPilot: false,
    expectedClose: "2026-06-01",
    updatedAt: "2026-05-20",
    createdAt: "2025-12-10",
    deviceUnitPrice: 466,
    devicePhases: [
      { period: "2026-Q3", units: 300 },
      { period: "2026-Q4", units: 300 },
      { period: "2027-Q2", units: 240 },
    ],
  },
  {
    id: "d_arctic",
    accountId: "a_arctic",
    parentDealId: null,
    ownerId: "u_elias",
    title: "Site maintenance pilot",
    stage: "lead",
    leadValidated: false,
    channel: "direct",
    isPilot: true,
    expectedClose: "2026-11-20",
    updatedAt: "2026-06-10",
    createdAt: "2026-05-08",
    deviceUnitPrice: 466,
    devicePhases: [
      { period: "2027-Q1", units: 240 },
      { period: "2027-Q3", units: 360 },
      { period: "2028-Q1", units: 280 },
    ],
  },
  {
    id: "d_halcyon",
    accountId: "a_halcyon",
    parentDealId: null,
    ownerId: "u_elias",
    title: "Antwerp pilot — facilities crews",
    stage: "final_negotiation",
    leadValidated: true,
    channel: "reseller",
    isPilot: true,
    expectedClose: "2026-08-29",
    updatedAt: "2026-06-10",
    createdAt: "2026-03-30",
    deviceUnitPrice: 312,
    devicePhases: [
      { period: "2026-Q3", units: 120 },
      { period: "2027-Q1", units: 360 },
      { period: "2027-Q3", units: 280 },
    ],
  },
];

export const seedServiceContracts: ServiceContract[] = [
  {
    id: "sc_nordcom_mdm",
    dealId: "d_nordcom",
    serviceId: "s_mdm",
    invoiceModel: "monthly_recurring",
    startDate: "2026-08-01",
    endDate: null,
    fixedValue: null,
    monthlyRate: 14,
    expectedDevices: 1660,
    phases: [
      { period: "2026-Q3", value: 16000 },
      { period: "2026-Q4", value: 34000 },
      { period: "2027-Q2", value: 58000 },
      { period: "2027-Q4", value: 70000 },
      { period: "2028-Q2", value: 70000 },
    ],
  },
  {
    id: "sc_nordcom_warranty",
    dealId: "d_nordcom",
    serviceId: "s_warranty",
    invoiceModel: "fixed_term",
    startDate: "2026-09-01",
    endDate: "2029-09-01",
    fixedValue: 96000,
    monthlyRate: null,
    expectedDevices: null,
    phases: [
      { period: "2026-Q4", value: 24000 },
      { period: "2027-Q2", value: 24000 },
      { period: "2027-Q4", value: 24000 },
      { period: "2028-Q2", value: 24000 },
    ],
  },
  {
    id: "sc_lumen_lifecycle",
    dealId: "d_lumen",
    serviceId: "s_lifecycle",
    invoiceModel: "fixed_term",
    startDate: "2026-07-01",
    endDate: "2029-07-01",
    fixedValue: 234000,
    monthlyRate: null,
    expectedDevices: null,
    phases: [
      { period: "2026-Q3", value: 28000 },
      { period: "2027-Q1", value: 60000 },
      { period: "2027-Q4", value: 64000 },
      { period: "2028-Q2", value: 42000 },
    ],
  },
  {
    id: "sc_lumen_bw_mdm",
    dealId: "d_lumen_bodyworn",
    serviceId: "s_mdm",
    invoiceModel: "monthly_recurring",
    startDate: "2026-08-01",
    endDate: null,
    fixedValue: null,
    monthlyRate: 14,
    expectedDevices: 840,
    phases: [
      { period: "2026-Q4", value: 12000 },
      { period: "2027-Q2", value: 30000 },
    ],
  },
  {
    id: "sc_halcyon_repair",
    dealId: "d_halcyon",
    serviceId: "s_repair",
    invoiceModel: "fixed_term",
    startDate: "2026-09-01",
    endDate: "2028-09-01",
    fixedValue: 72000,
    monthlyRate: null,
    expectedDevices: null,
    phases: [
      { period: "2026-Q4", value: 14000 },
      { period: "2027-Q1", value: 20000 },
      { period: "2027-Q3", value: 22000 },
    ],
  },
  {
    id: "sc_vektor_sim",
    dealId: "d_vektor",
    serviceId: "s_sim",
    invoiceModel: "monthly_recurring",
    startDate: "2026-10-01",
    endDate: null,
    fixedValue: null,
    monthlyRate: 6,
    expectedDevices: 1260,
    phases: [
      { period: "2026-Q4", value: 8000 },
      { period: "2027-Q1", value: 18000 },
      { period: "2027-Q3", value: 24000 },
    ],
  },
];

export const seedCases: CaseRecord[] = [
  {
    id: "case_3041", ref: "CASE-3041", accountId: "a_nordcom", dealId: "d_nordcom", serviceId: "s_mdm", ownerId: "u_sara", contactId: "c_nordcom_1",
    title: "Battery policy clarification for cold-storage crews", status: "in_progress", priority: "high", escalated: false,
    thirdPartyRef: null, slaDeadline: "2026-06-15", createdAt: "2026-06-04", updatedAt: "2026-06-11",
    notes: [
      { author: "Sara Miettinen", body: "Customer asked for a written battery-retention policy for −20°C operation.", when: "04 Jun 2026", internal: false },
      { author: "Sara Miettinen", body: "Engineering confirmed the XR-21 holds spec to −20°C; drafting the customer-facing note.", when: "11 Jun 2026", internal: true },
    ],
  },
  {
    id: "case_2987", ref: "CASE-2987", accountId: "a_nordcom", dealId: "d_nordcom", serviceId: "s_mdm", ownerId: "u_oskari", contactId: "c_nordcom_2",
    title: "MDM enrolment failed on 4 devices", status: "open", priority: "medium", escalated: false,
    thirdPartyRef: null, slaDeadline: "2026-06-18", createdAt: "2026-06-09", updatedAt: "2026-06-09",
    notes: [
      { author: "Tobias Reiner", body: "Four units stuck at the enrolment screen after the depot reset.", when: "09 Jun 2026", internal: false },
    ],
  },
  {
    id: "case_2890", ref: "CASE-2890", accountId: "a_lumen", serviceId: "s_lifecycle", ownerId: "u_sara", contactId: "c_lumen_3",
    title: "Encryption attestation required for renewal", status: "escalated", priority: "critical", escalated: true,
    thirdPartyRef: "ATT-7741", slaDeadline: "2026-06-12", createdAt: "2026-06-02", updatedAt: "2026-06-12",
    notes: [
      { author: "Gareth Pugh", body: "Legal needs a signed encryption attestation before the frame can be renewed.", when: "02 Jun 2026", internal: false },
      { author: "Sara Miettinen", body: "Escalated to the security team for the signed attestation pack (ref ATT-7741).", when: "08 Jun 2026", internal: true },
      { author: "Sara Miettinen", body: "SLA breached today — chasing security for an ETA.", when: "12 Jun 2026", internal: true },
    ],
  },
  {
    id: "case_2855", ref: "CASE-2855", accountId: "a_lumen", serviceId: "s_lifecycle", ownerId: "u_oskari", contactId: "c_lumen_1",
    title: "Spare-pool replenishment for two divisions", status: "open", priority: "high", escalated: false,
    thirdPartyRef: null, slaDeadline: "2026-06-16", createdAt: "2026-06-05", updatedAt: "2026-06-09",
    notes: [
      { author: "DCI Rowan Hale", body: "Two divisions are below the agreed spare-pool floor.", when: "05 Jun 2026", internal: false },
    ],
  },
  {
    id: "case_3120", ref: "CASE-3120", accountId: "a_vektor", serviceId: "s_sim", ownerId: "u_oskari", contactId: "c_vektor_1",
    title: "SIM provisioning delay on reseller order", status: "escalated", priority: "medium", escalated: true,
    thirdPartyRef: "ARQ-5521", slaDeadline: "2026-06-19", createdAt: "2026-06-08", updatedAt: "2026-06-11",
    notes: [
      { author: "Henrik Sø", body: "120 SIMs not yet active; drivers can't go live.", when: "08 Jun 2026", internal: false },
      { author: "Oskari Lehto", body: "Raised with the connectivity provider, ticket ARQ-5521.", when: "11 Jun 2026", internal: true },
    ],
  },
  {
    id: "case_3066", ref: "CASE-3066", accountId: "a_halcyon", serviceId: "s_repair", ownerId: "u_oskari", contactId: "c_halcyon_2",
    title: "Replacement units for water-damaged batch", status: "resolved", priority: "medium", escalated: false,
    thirdPartyRef: null, slaDeadline: "2026-05-30", createdAt: "2026-05-20", updatedAt: "2026-05-29",
    notes: [
      { author: "Anouk Jansen", body: "Eight units water-damaged on a flooded site.", when: "20 May 2026", internal: false },
      { author: "Oskari Lehto", body: "Swap shipped and confirmed received. Closing.", when: "29 May 2026", internal: false },
    ],
  },
];
export const seedOffers: Offer[] = [
  {
    id: "off_1188", ref: "OFF-1188", dealId: "d_nordcom", createdById: "u_aino", version: 3,
    status: "made", discountPct: 12,
    justification: "Wave-2 volume commitment of 1,660 devices and a 3-year MDM commitment; matching the wave-1 pilot pricing to keep the rollout on a single standard.",
    lockedAt: null, createdAt: "2026-06-11",
    lines: [
      { productId: "p_xr21", serviceId: null, label: "HMD XR-21 rugged 5G", unitPrice: 466, quantity: 1660, discountPct: 12 },
      { productId: "p_sled", serviceId: null, label: "HMD Edge scanner sled", unitPrice: 128, quantity: 400, discountPct: 10 },
      { productId: null, serviceId: "s_mdm", label: "Secure MDM (monthly, per device)", unitPrice: 14, quantity: 1660, discountPct: 0 },
      { productId: null, serviceId: "s_warranty", label: "Extended Warranty (3 yr)", unitPrice: 96000, quantity: 1, discountPct: 0 },
    ],
    approvals: [
      { stepOrder: 1, roleRequired: "sales_rep", decidedById: "u_aino", decision: "approved", note: null, decidedAt: "2026-06-11" },
      { stepOrder: 2, roleRequired: "sales_manager", decidedById: "u_mikael", decision: "approved", note: "Volume and term justify the discount.", decidedAt: "2026-06-12" },
    ],
  },
  {
    id: "off_1099", ref: "OFF-1099", dealId: "d_lumen", createdById: "u_aino", version: 1,
    status: "pending_manager", discountPct: 8,
    justification: "Public-sector frame renewal; the customer is holding to last frame's unit price and a competitor is in the RFP.",
    lockedAt: null, createdAt: "2026-06-09",
    lines: [
      { productId: "p_t30", serviceId: null, label: "HMD T-30 field tablet", unitPrice: 612, quantity: 1820, discountPct: 8 },
      { productId: null, serviceId: "s_lifecycle", label: "Device Lifecycle Management (3 yr)", unitPrice: 234000, quantity: 1, discountPct: 0 },
    ],
    approvals: [
      { stepOrder: 1, roleRequired: "sales_rep", decidedById: "u_aino", decision: "approved", note: null, decidedAt: "2026-06-09" },
      { stepOrder: 2, roleRequired: "sales_manager", decidedById: null, decision: null, note: null, decidedAt: null },
    ],
  },
  {
    id: "off_1175", ref: "OFF-1175", dealId: "d_halcyon", createdById: "u_elias", version: 2,
    status: "made", discountPct: 5,
    justification: "Pilot pricing for one market with two committed follow-on markets in the account plan.",
    lockedAt: null, createdAt: "2026-05-28",
    lines: [
      { productId: "p_pulse", serviceId: null, label: "HMD Pulse handheld", unitPrice: 312, quantity: 760, discountPct: 5 },
      { productId: null, serviceId: "s_repair", label: "Onsite Repair & Swap", unitPrice: 72000, quantity: 1, discountPct: 0 },
    ],
    approvals: [
      { stepOrder: 1, roleRequired: "sales_rep", decidedById: "u_elias", decision: "approved", note: null, decidedAt: "2026-05-28" },
      { stepOrder: 2, roleRequired: "sales_manager", decidedById: "u_mikael", decision: "approved", note: "Follow-on commitment recorded.", decidedAt: "2026-06-04" },
    ],
  },
  {
    id: "off_1204", ref: "OFF-1204", dealId: "d_vektor", createdById: "u_elias", version: 3,
    status: "sales_rep", discountPct: 0, justification: null, lockedAt: null, createdAt: "2026-06-12",
    lines: [
      { productId: "p_pulse", serviceId: null, label: "HMD Pulse handheld", unitPrice: 312, quantity: 1260, discountPct: 0 },
      { productId: null, serviceId: "s_sim", label: "SIM Provisioning (monthly, per device)", unitPrice: 6, quantity: 1260, discountPct: 0 },
    ],
    approvals: defaultOfferWorkflow(),
  },
];

export const seedActivities: Activity[] = [
  { id: "act_1", accountId: "a_nordcom", dealId: "d_nordcom", actorId: null, kind: "ai", summary: "AI account review generated: confirm pilot acceptance criteria before Friday.", when: "13 Jun 2026", isAi: true },
  { id: "act_2", accountId: "a_nordcom", dealId: "d_nordcom", actorId: "u_aino", kind: "stage", summary: "Moved Field crew rollout — wave 2 to Customer testing.", when: "26 May 2026", isAi: false },
  { id: "act_3", accountId: "a_nordcom", dealId: "d_nordcom", actorId: "u_aino", kind: "meeting", summary: "Technical review with field operations.", when: "16 May 2026", isAi: false },
  { id: "act_4", accountId: "a_nordcom", dealId: "d_nordcom", actorId: "u_aino", kind: "offer", summary: "Offer OFF-1188 v3 sent to procurement.", when: "11 Jun 2026", isAi: false },
  { id: "act_5", accountId: "a_nordcom", dealId: "d_nordcom", actorId: "u_sara", kind: "case", summary: "CASE-3041 opened: battery policy clarification.", when: "04 Jun 2026", isAi: false },
  { id: "act_6", accountId: "a_vektor", dealId: "d_vektor", actorId: null, kind: "ai", summary: "AI next action: ask the reseller to confirm the customer-test window.", when: "13 Jun 2026", isAi: true },
  { id: "act_7", accountId: "a_vektor", dealId: "d_vektor", actorId: "u_elias", kind: "stage", summary: "Moved Driver terminal refresh to Offer.", when: "02 Jun 2026", isAi: false },
  { id: "act_8", accountId: "a_vektor", dealId: "d_vektor", actorId: "u_oskari", kind: "case", summary: "CASE-3120 escalated to connectivity provider.", when: "11 Jun 2026", isAi: false },
  { id: "act_9", accountId: "a_lumen", dealId: "d_lumen", actorId: "u_sara", kind: "case", summary: "CASE-2890 SLA breached on encryption attestation.", when: "12 Jun 2026", isAi: false },
  { id: "act_10", accountId: "a_lumen", dealId: "d_lumen", actorId: "u_aino", kind: "stage", summary: "Moved Frame renewal to Final negotiation.", when: "28 May 2026", isAi: false },
  { id: "act_11", accountId: "a_lumen", dealId: "d_lumen", actorId: null, kind: "ai", summary: "AI risk flag: close date passed; no revised procurement date recorded.", when: "13 Jun 2026", isAi: true },
  { id: "act_12", accountId: "a_arctic", dealId: "d_arctic", actorId: "u_elias", kind: "meeting", summary: "Discovery call booked for 17 June.", when: "10 Jun 2026", isAi: false },
  { id: "act_13", accountId: "a_arctic", dealId: "d_arctic", actorId: "u_elias", kind: "note", summary: "Account created from inbound enquiry.", when: "08 May 2026", isAi: false },
  { id: "act_14", accountId: "a_halcyon", dealId: "d_halcyon", actorId: "u_elias", kind: "offer", summary: "Offer OFF-1175 approved and locked.", when: "06 Jun 2026", isAi: false },
  { id: "act_15", accountId: "a_halcyon", dealId: "d_halcyon", actorId: "u_elias", kind: "stage", summary: "Moved Antwerp pilot to Customer testing.", when: "28 May 2026", isAi: false },
];

export const seedAiInsights: AiInsight[] = [
  {
    id: "ai_nordcom_next", accountId: "a_nordcom", dealId: "d_nordcom", caseId: null, type: "next_action",
    headline: "Confirm pilot acceptance criteria and book the technical review before Friday.",
    body: "Wave-2 has been in Customer test since 21 May with no outcome recorded and an expected close of 18 July. Locking acceptance criteria now keeps the close date credible.",
    confidence: 0.82,
    evidence: [
      "Customer test began 21 May; no outcome has been recorded.",
      "CASE-3041 asks for battery-policy confirmation, still in progress.",
      "Expected close is 35 days away.",
    ],
    sources: [
      { title: "Deal timeline", detail: "Stage entered Customer test 21 May" },
      { title: "CASE-3041", detail: "Open clarification blocking sign-off" },
    ],
    status: "pending_review",
    draftEmail: "Hi Marit,\n\nAhead of the wave-2 sign-off, could we lock the acceptance criteria and book a 30-minute technical review this week? I'll bring the written cold-storage battery policy your team asked for.\n\nBest,\nAino",
  },
  {
    id: "ai_nordcom_enrich", accountId: "a_nordcom", dealId: null, caseId: null, type: "enrichment",
    headline: "Nordcom is expanding field operations into Austria.",
    body: "Public sources indicate two new Austrian depots and an active move from consumer phones to managed rugged devices — consistent with the wave-2 expansion.",
    confidence: 0.74,
    evidence: [
      "Press: announced expansion into Austria with two new depots (3 weeks ago).",
      "Hiring: new Head of IT Operations from a logistics competitor.",
    ],
    sources: [
      { title: "nordcom.example", detail: "Company site — locations, news" },
      { title: "Trade press", detail: "Austria depot expansion" },
    ],
    status: "pending_review",
  },
  {
    id: "ai_lumen_risk", accountId: "a_lumen", dealId: "d_lumen", caseId: null, type: "risk_flag",
    headline: "Frame renewal is past its close date with legal review unresolved.",
    body: "Expected close was 6 June. Legal review is still open via CASE-2890 (SLA breached). Update the close date or record the procurement blocker before the forecast review.",
    confidence: 0.88, severity: "high",
    evidence: [
      "Expected close date was 6 June; today is 13 June.",
      "CASE-2890 encryption attestation SLA breached.",
      "No revised procurement date is recorded.",
    ],
    sources: [
      { title: "Deal record", detail: "expected_close = 2026-06-06" },
      { title: "CASE-2890", detail: "Escalated, SLA breached" },
    ],
    status: "pending_review",
  },
  {
    id: "ai_vektor_next", accountId: "a_vektor", dealId: "d_vektor", caseId: null, type: "next_action",
    headline: "Ask the reseller to confirm the customer-test window and decision owner.",
    body: "Reseller deals move from Customer test straight to Won. The offer is opened and pricing approved, so the next valid step is to set the test window.",
    confidence: 0.7,
    evidence: [
      "Offer OFF-1204 opened by the reseller yesterday.",
      "Customer test is the next valid reseller stage.",
      "Pricing approval is complete.",
    ],
    sources: [{ title: "Offer OFF-1204", detail: "Opened 12 Jun" }],
    status: "pending_review",
  },
  {
    id: "ai_arctic_enrich", accountId: "a_arctic", dealId: "d_arctic", caseId: null, type: "next_action",
    headline: "Capture the expected device rollout by site after the discovery call.",
    body: "Arctic Grid has three operating sites and fresh funding but no device trajectory entered. Capture per-site volumes before quoting.",
    confidence: 0.66,
    evidence: [
      "Three operating sites listed on the account.",
      "No device trajectory has been entered.",
      "Discovery call booked for 17 June.",
    ],
    sources: [{ title: "Account record", detail: "3 sites, trajectory empty" }],
    status: "pending_review",
  },
  {
    id: "ai_halcyon_next", accountId: "a_halcyon", dealId: "d_halcyon", caseId: null, type: "next_action",
    headline: "Prepare the follow-on order structure before the pilot review.",
    body: "The Antwerp pilot is in Customer test with two follow-on markets identified. Structuring follow-on orders linked to this opportunity keeps the forecast cumulative.",
    confidence: 0.71,
    evidence: [
      "Pilot includes 120 devices in one market.",
      "Account plan identifies two follow-on markets.",
      "Reseller margin approved through OFF-1175.",
    ],
    sources: [{ title: "Account plan", detail: "Two follow-on markets" }],
    status: "pending_review",
  },
];

export const seedNotifications: Notification[] = [
  { id: "n_1", userId: "u_aino", kind: "ai", body: "AI insights updated for Nordcom Mobility.", read: false, when: "13 Jun, 09:42", link: { screen: "account", id: "a_nordcom" } },
  { id: "n_2", userId: "u_aino", kind: "stage", body: "Field crew rollout — wave 2 has not moved in 18 days.", read: false, when: "13 Jun, 08:00", link: { screen: "account", id: "a_nordcom" } },
  { id: "n_3", userId: "u_aino", kind: "offer", body: "OFF-1188 cleared Sales Manager approval — now with Finance.", read: true, when: "12 Jun, 16:20", link: { screen: "offers", id: "off_1188" } },
  { id: "n_4", userId: "u_mikael", kind: "offer", body: "OFF-1099 (Lumen, 8% discount) is awaiting your approval.", read: false, when: "12 Jun, 11:05", link: { screen: "offers", id: "off_1099" } },
  { id: "n_5", userId: "u_veera", kind: "offer", body: "OFF-1188 (Nordcom, 12% discount) is awaiting Finance approval.", read: false, when: "12 Jun, 16:20", link: { screen: "offers", id: "off_1188" } },
  { id: "n_6", userId: "u_sara", kind: "case", body: "CASE-2890 has breached its SLA.", read: false, when: "12 Jun, 09:00", link: { screen: "case", id: "case_2890" } },
  { id: "n_7", userId: "u_oskari", kind: "case", body: "CASE-3120 escalation acknowledged by the provider.", read: true, when: "11 Jun, 14:10", link: { screen: "case", id: "case_3120" } },
];
